# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ed61fec6cb90b5baf20a5414f00a1a1757bf196300be7ce6644475c707781898f40356921af17d455900de7bc37aae91336b21dfa0dcbc85933fc334843efc8

test:
  secret_key_base: beb0e5ea7bba1a31cd46a9838d977b8ee666842732d5cbe833226732ee2346ddc8f9897cf7885a6f06c672a0412475c9f97554e4adc7c4ef860eab8b5fd9d521

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
