# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(email:"wewef@yahoo.com", username:"Eric", password:"123456", role: 3)
User.create(email:"ewfw@yahoo.com", username:"Kevin", password:"123456", role: 2)
User.create(email:"wefwef@yahoo.com", username:"Justin", password:"123456", role: 1)

Category.create(name:"Math")
Category.create(name:"Vocab")
Category.create(name:"Books")


Subcategory.create(name:"Algebra", category_id: 1)
Subcategory.create(name:"Geometry", category_id: 1)
Subcategory.create(name:"Biology", category_id: 2)
Subcategory.create(name:"Harry Potter and the Philosopher's Stone", category_id: 3)



    Concept.create(name:"Addition", subcategory_id:1, description:"Adding numbers")
      Question.create(inquest:"What is 1 + 1", answer: "2", concept_id:1, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "4", question_id: 1)
        RandomQuestion.create(name: "6", question_id: 1)
        RandomQuestion.create(name: "8", question_id: 1)
      Question.create(inquest:"What is 5 + 2", answer: "7", concept_id:1, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "3", question_id: 2)
        RandomQuestion.create(name: "9", question_id: 2)
        RandomQuestion.create(name: "4", question_id: 2)
      Question.create(inquest:"What is 6 + 4", answer: "10", concept_id:1, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "9", question_id: 3)
        RandomQuestion.create(name: "14", question_id: 3)
        RandomQuestion.create(name: "6", question_id: 3)
      Question.create(inquest:"What is 8 + 17", answer: "25", concept_id:1, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "23", question_id: 4)
        RandomQuestion.create(name: "27", question_id: 4)
        RandomQuestion.create(name: "18", question_id: 4)
      Question.create(inquest:"What is 2 + 1", answer: "3", concept_id:1, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "5", question_id: 5)
        RandomQuestion.create(name: "2", question_id: 5)
        RandomQuestion.create(name: "1", question_id: 5)
    Concept.create(name:"Subtraction", subcategory_id:1, description:"subtracting numbers")
      Question.create(inquest:"What is 5 - 1", answer: "4", concept_id:2, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "3", question_id: 6)
        RandomQuestion.create(name: "9", question_id: 6)
        RandomQuestion.create(name: "4", question_id: 6)
      Question.create(inquest:"What is 51 - 22", answer: "29", concept_id:2, user_id:1, difficulty: 2)
        RandomQuestion.create(name: "24", question_id: 7)
        RandomQuestion.create(name: "18", question_id: 7)
        RandomQuestion.create(name: "26", question_id: 7)
      Question.create(inquest:"What is 6 - 5", answer: "1", concept_id:2, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "2", question_id: 8)
        RandomQuestion.create(name: "-3", question_id: 8)
        RandomQuestion.create(name: "4", question_id: 8)
      Question.create(inquest:"What is 2 - 11", answer: "-9", concept_id:2, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "6", question_id: 9)
        RandomQuestion.create(name: "12", question_id: 9)
        RandomQuestion.create(name: "5", question_id: 9)
      Question.create(inquest:"What is 12 - 9", answer: "3", concept_id:2, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "5", question_id: 10)
        RandomQuestion.create(name: "21", question_id: 10)
        RandomQuestion.create(name: "6", question_id: 10)
      Question.create(inquest:"What is 5 - 41", answer: "-36", concept_id:2, user_id:1, difficulty: 2)
        RandomQuestion.create(name: "36", question_id: 11)
        RandomQuestion.create(name: "35", question_id: 11)
        RandomQuestion.create(name: "-31", question_id: 11)
      Question.create(inquest:"What is 9 - 17", answer: "-8", concept_id:2, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "-9", question_id: 12)
        RandomQuestion.create(name: "26", question_id: 12)
        RandomQuestion.create(name: "23", question_id: 12)
      Question.create(inquest:"What is 2 - 5", answer: "-3", concept_id:2, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "-7", question_id: 13)
        RandomQuestion.create(name: "-4", question_id: 13)
        RandomQuestion.create(name: "5", question_id: 13)
    Concept.create(name:"Division", subcategory_id:1, description:"dividing numbers")
      Question.create(inquest:"What is 10 / 1", answer: "10", concept_id:3, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "9", question_id: 14)
        RandomQuestion.create(name: "11", question_id: 14)
        RandomQuestion.create(name: "4", question_id: 14)
      Question.create(inquest:"What is 66 / 22", answer: "3", concept_id:3, user_id:1, difficulty: 2)
        RandomQuestion.create(name: "4", question_id: 15)
        RandomQuestion.create(name: "44", question_id: 15)
        RandomQuestion.create(name: "23", question_id: 15)
      Question.create(inquest:"What is 10 / 5", answer: "2", concept_id:3, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "5", question_id: 16)
        RandomQuestion.create(name: "4", question_id: 16)
        RandomQuestion.create(name: "12", question_id: 16)
      Question.create(inquest:"What is 12 / 2", answer: "6", concept_id:3, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "10", question_id: 17)
        RandomQuestion.create(name: "8", question_id: 17)
        RandomQuestion.create(name: "3", question_id: 17)
      Question.create(inquest:"What is 78 / 2", answer: "39", concept_id:3, user_id:1, difficulty: 2)
        RandomQuestion.create(name: "76", question_id: 18)
        RandomQuestion.create(name: "42", question_id: 18)
        RandomQuestion.create(name: "32", question_id: 18)
      Question.create(inquest:"What is 20 / 4", answer: "5", concept_id:3, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "6", question_id: 19)
        RandomQuestion.create(name: "4", question_id: 19)
        RandomQuestion.create(name: "12", question_id: 19)
      Question.create(inquest:"What is 75 / 5", answer: "15", concept_id:3, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "9", question_id: 20)
        RandomQuestion.create(name: "70", question_id: 20)
        RandomQuestion.create(name: "25", question_id: 20)
    Concept.create(name:"Multiplication", subcategory_id:1, description:"multiplying numbers")
      Question.create(inquest:"What is 5 * 1", answer: "5", concept_id:4, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "4", question_id: 21)
        RandomQuestion.create(name: "20", question_id: 21)
        RandomQuestion.create(name: "3", question_id: 21)
      Question.create(inquest:"What is 24 * 10", answer: "240", concept_id:4, user_id:1, difficulty: 2)
        RandomQuestion.create(name: "14", question_id: 22)
        RandomQuestion.create(name: "22", question_id: 22)
        RandomQuestion.create(name: "220", question_id: 22)
      Question.create(inquest:"What is 6 * 5", answer: "30", concept_id:4, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "25", question_id: 23)
        RandomQuestion.create(name: "23", question_id: 23)
        RandomQuestion.create(name: "19", question_id: 23)
      Question.create(inquest:"What is 2 * 11", answer: "22", concept_id:4, user_id:1, difficulty: 1)
        RandomQuestion.create(name: "42", question_id: 24)
        RandomQuestion.create(name: "15", question_id: 24)
        RandomQuestion.create(name: "13", question_id: 24)
      Question.create(inquest:"What is 150 * 2", answer: "300", concept_id:4, user_id:1, difficulty: 2)
        RandomQuestion.create(name: "42", question_id: 25)
        RandomQuestion.create(name: "280", question_id: 25)
        RandomQuestion.create(name: "200", question_id: 25)
      Question.create(inquest:"What is 8 * 7", answer: "56", concept_id:4, user_id:1, difficulty: 2)
        RandomQuestion.create(name: "42", question_id: 26)
        RandomQuestion.create(name: "12", question_id: 26)
        RandomQuestion.create(name: "13", question_id: 26)

      Concept.create(name:"Chapter 1: The Boy Who Lived", subcategory_id:4, description:"The Boy Who Lived")
        Question.create(inquest:"What drill company does Vernon Dursely work for?", answer: "Grunnings", concept_id:5, user_id:1, difficulty: 4)
          RandomQuestion.create(name: "Ford", question_id: 27)
          RandomQuestion.create(name: "Hogwarts", question_id: 27)
          RandomQuestion.create(name: "Acker", question_id: 27)
        Question.create(inquest:"What is a muggle?", answer: "Non-magic folk", concept_id:5, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Someone who muggles", question_id: 28)
          RandomQuestion.create(name: "Magic user", question_id: 28)
          RandomQuestion.create(name: "Doge", question_id: 28)
        Question.create(inquest:"Where do the Durselys live?", answer: "4 Privet Drive", concept_id:5, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "4 Private Drive", question_id: 29)
          RandomQuestion.create(name: "524 Broadway", question_id: 29)
          RandomQuestion.create(name: "America", question_id: 29)
        Question.create(inquest:"What does Dumbledore use to syphon all the street lights?", answer: "Deluminator", concept_id:5, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Wand", question_id: 30)
          RandomQuestion.create(name: "Staff", question_id: 30)
          RandomQuestion.create(name: "Magic", question_id: 30)
        Question.create(inquest:"Who killed Lily and James Potter?", answer: "Voldemort", concept_id:5, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Harry Potter", question_id: 31)
          RandomQuestion.create(name: "Doge", question_id: 31)
          RandomQuestion.create(name: "Harambe", question_id: 31)
      Concept.create(name:"Chapter 2: The Vanishing Glass", subcategory_id:4, description:"The Vanishing Glass")
        Question.create(inquest:"How long has Harry lived at the Durselys?", answer: "10 years", concept_id:6, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "8 years", question_id: 32)
          RandomQuestion.create(name: "15 years", question_id: 32)
          RandomQuestion.create(name: "12 years", question_id: 32)
        Question.create(inquest:"Where does Harry live at the Durseyls?", answer: "The cupboard under the stairs", concept_id:6, user_id:1, difficulty: 2)
          RandomQuestion.create(name: "Kitchen", question_id: 33)
          RandomQuestion.create(name: "With Dudley", question_id: 33)
          RandomQuestion.create(name: "Dudleys Other room", question_id: 33)
        Question.create(inquest:"What is Harry's scar in the form of?", answer: "Lightning", concept_id:6, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Fire", question_id: 34)
          RandomQuestion.create(name: "Water", question_id: 34)
          RandomQuestion.create(name: "Darkness", question_id: 34)
        Question.create(inquest:"Who lives next to the Durselys", answer: "Figgs", concept_id:6, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Dinklebergs", question_id: 35)
          RandomQuestion.create(name: "Squidward", question_id: 35)
          RandomQuestion.create(name: "Cattermoles", question_id: 35)
        Question.create(inquest:"What did Harry dream about last night?", answer: "A motarbike", concept_id:6, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Delacour", question_id: 36)
          RandomQuestion.create(name: "Cake", question_id: 36)
          RandomQuestion.create(name: "Dursleys", question_id: 36)
        Question.create(inquest:"What kind of snake did Harry see?", answer: "Boa Constrictor", concept_id:6, user_id:1, difficulty: 2)
          RandomQuestion.create(name: "Python", question_id: 37)
          RandomQuestion.create(name: "Taipan", question_id: 37)
          RandomQuestion.create(name: "Alethinophidia", question_id: 37)
        Question.create(inquest:"How long did Vernon punish Harry with no meals for?", answer: "1 week", concept_id:6, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "1 day", question_id: 38)
          RandomQuestion.create(name: "5 days", question_id: 38)
          RandomQuestion.create(name: "2 weeks", question_id: 38)
      Concept.create(name:"Chapter 3: The Letters from No One", subcategory_id:4, description:"The Letters from No One")
        Question.create(inquest:"What season was it when Harry was finally able to come out of his cupboard?", answer: "Summer", concept_id:7, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Winter", question_id: 39)
          RandomQuestion.create(name: "Autumn", question_id: 39)
          RandomQuestion.create(name: "Spring", question_id: 39)
        Question.create(inquest:"Where is Dudley going to school?", answer: "Smeltings Academy", concept_id:7, user_id:1, difficulty: 2)
          RandomQuestion.create(name: "Country School", question_id: 40)
          RandomQuestion.create(name: "Elk Valley", question_id: 40)
          RandomQuestion.create(name: "Oak Ridge", question_id: 40)
        Question.create(inquest:"Where is Harry going to school?", answer: "Stonewall High", concept_id:7, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Hogwarts", question_id: 41)
          RandomQuestion.create(name: "Angelwood", question_id: 41)
          RandomQuestion.create(name: "Silver Valley", question_id: 41)
        Question.create(inquest:"Why did Vernon decide to leave the house?", answer: "Attacked by letters", concept_id:7, user_id:1, difficulty: 1)
          RandomQuestion.create(name: "Felt like it", question_id: 42)
          RandomQuestion.create(name: "Doesn't like Harry", question_id: 42)
          RandomQuestion.create(name: "Vaction", question_id: 42)
        Question.create(inquest:"How old is Harry turning?", answer: "11", concept_id:7, user_id:1, difficulty: 2)
          RandomQuestion.create(name: "9", question_id: 43)
          RandomQuestion.create(name: "14", question_id: 43)
          RandomQuestion.create(name: "15", question_id: 43)
